### ISSUE TITLE
"npm run serve" and "gulp serve" fail to start a browsersync -- for me at least

### ISSUE THREAD

**Issue by durbonas** [FountainJS/generator-fountain-systemjs#39]
Hey, 

Big fans of your generators guys!

Just gave this one a shot and everything installed just fine but when I run a serve command, no new browser window starts up like usual. If I then manually open a window and put in the url http://localhost:3000/ - then I see the page no problem. Then if a make a change to the stylesheet, it does show in terminal "[BS] Reloading Browsers" but does not refresh the broswer window to show the change. 

Thoughts?

**Comment by zckrs** [comment]
Hi 

>Big fans of your generators guys!

Thank  you

Can you provide more information? cmd run? options selected? node, npm version?

**Comment by durbonas** [comment]
Sure, my install was as follows:

Framework: Angular 2
Modules manager: Webpack with NPM
CSS preprocessor: SASS
JS preprocessor: TypeScript
Sample app: A working landing page

and my npm versions is 3.9.3

I've tried both commands "npm run serve" and "gulp serve", nothing else.

Here is how my terminal reads on: 

gulp serve

[16:39:56] Loading /Users/durbonas/ang2/gulp_tasks/browsersync.js
[16:39:56] Loading /Users/durbonas/ang2/gulp_tasks/karma.js
[16:39:56] Loading /Users/durbonas/ang2/gulp_tasks/misc.js
[16:39:56] Loading /Users/durbonas/ang2/gulp_tasks/webpack.js
[16:39:57] Using gulpfile ~/ang2/gulpfile.js
[16:39:57] Starting 'serve'...
[16:39:57] Starting 'webpack:watch'...
ts-loader: Using typescript@1.8.10 and /Users/durbonas/ang2/conf/ts.conf.json
[16:40:05] Time: 8410ms
     Asset       Size  Chunks             Chunk Names
  index.js    7.75 MB       0  [emitted]  main
index.html  305 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.36 MB       0
[16:40:05] Finished 'webpack:watch' after 8.43 s
[16:40:05] Starting 'watch'...
[16:40:05] Finished 'watch' after 95 ms
[16:40:05] Starting 'browsersync'...
[16:40:06] Finished 'browsersync' after 19 ms
[16:40:06] Finished 'serve' after 8.55 s
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.111.87:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.111.87:3001
 ---------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: src 
 **--- THIS IS WERE IT HANGS UNTIL I MAKE A CHANGE (like below), BUT NOTHING HAPPENS WITH THE BROWSER**
[16:47:24] Time: 1111ms
   Asset     Size  Chunks             Chunk Names
index.js  7.75 MB       0  [emitted]  main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.36 MB       0
[BS] Reloading Browsers...

Hope that helps

**Comment by zckrs** [comment]
I will try in local.

But question. Why do you post issue here(the systemjs repo) instead of https://github.com/FountainJS/generator-fountain-angular2 or https://github.com/FountainJS/generator-fountain-webpack ?

**Comment by durbonas** [comment]
Sorry, I really don't use github much other then to reference things. I wasn't aware of those other pages I guess.

**Comment by zckrs** [comment]
@durbonas we have just release a new version 0.5.3 you can install it by `npm install --global generator-fountain-webapp`

I try in local your issue:

* Auto open tab when `npm run serve` are deactivate in "conf/browsersync.conf.js". You can enable it by change `open: false` by `open: true`

* Browsersync reload as expected the page when I edit stylesheet in "src/index.scss".

**Comment by durbonas** [comment]
OK, so now it will launch a browser window on npm run serve, but won't refresh page on any changes :(

**Comment by zckrs** [comment]
We have land a new version v0.5.4 can you check if your issue is solved ?

**Comment by zckrs** [comment]
IMO fixed

**Comment by methgaard** [comment]
Hi @zckrs . I experience the same issue. Not at first, but after working for a few hours. (magic).
I have event tried generating a new project, same this happens. i have made no changes to the project
Have you been looking further into this?
